version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    filefmt:
        format: '%(asctime)s, %(message)s'
        datefmt: '%Y/%m/%d, %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: filefmt
        filename: logs/detect.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
loggers:
    sampleLogger:
        level: ERROR
        handlers: [console]
    
root:
    level: DEBUG
    handlers: [console, file]
